'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Books', [
      {author: 'Stephen King', title: 'The Stand', publisher: 'Doubleday', publicationDate: new Date('October 3, 1978'), synopsis: 'Good vs Evil in the post-apocalypse', tagId: null, coverArt: '../images/the-stand.jpg', createdAt: new Date(), updatedAt: new Date()},
      {author: 'Anne Rice', title: 'Blood Communion', publisher: 'Knopf', publicationDate: new Date('October 2, 2018'), synopsis: 'The novel is a tale told by the vampire Lestat de Lioncourt, in which he recounts his confrontations with the villainous vampire Rhoshamandes', tagId: null, coverArt: '../images/blood-communion.jpg', createdAt: new Date(), updatedAt: new Date()},
      {author: 'Victor Kelleher', title: 'Born of the Sea', publisher: 'Viking Press', publicationDate: new Date('July 10, 2003'), synopsis: "follows the story of Madeleine Sauvage, Frankenstein's bride from Mary Shelleys story, if she wasnt destroyed and laying in the bottom of the sea and goes out in search of her creator", tagId: null, coverArt: "../images/born-of-the-sea.jpg", createdAt: new Date(), updatedAt: new Date()},
      {author: 'Albert Sánchez Piñol', title: 'Cold Skin', publisher: 'Canongate Books', publicationDate: new Date('August 12, 2002'), synopsis: 'The novel chronicles the story of a former fighter for the independence of Ireland who, unmotivated by the events of the Western World, decides to escape from the society in which he lives. He accepts a job offer as a weather official on a remote island in the south Atlantic close to the Antarctic Circle.', tagId: null, coverArt: "../images/cold-skin.jpg", createdAt: new Date(), updatedAt: new Date()},
      {author: 'Dean Koontz', title: 'False Memory', publisher: '	Cemetery Dance Publications and Bantam Books', publicationDate: new Date('July 4, 1991'), synopsis: "Martie Rhodes helps her friend Susan Jagger, who suffers from agoraphobia, attend visits to psychologist Dr. Ahriman. Martie's husband, Dusty Rhodes, tries to help his brother Skeet, by providing employment in his painting business. Skeet had been in Drug rehabilitation previously, and when he first appears in the story, he is high (apparently relapsed) and tries to commit suicide by jumping off a roof. Dusty (who falls off the roof in an attempt to save Skeet, ends up saving both himself and Skeet) decides to take him back to rehab due to Skeet's actions.", tagId: null, coverArt: "../images/false-memory.jpg", createdAt: new Date(), updatedAt: new Date()},
      {author: 'Charlie Higson', title: 'The Fear', publisher: 'Puffin Books', publicationDate: new Date('September 15, 2011'), synopsis: "The Fear starts a few days before Small Sam and the Kid arrive at the Tower of London, at the end of The Dead, and another few days before the events of The Enemy (with both books merging into each other near the middle). A prologue introduces a new zombie called 'The Collector', a massive father who collects 'toys' (kids), plays with them until they break (tortures them until they die), and eats them. He finds two children and adds them to his 'collection', as described in the prologue of the book.", tagId: null, coverArt: "../images/the-fear.jpg", createdAt: new Date(), updatedAt: new Date()},
      {author: 'John Metcalfe', title: 'The Feasting Dead', publisher: 'Arkham House', publicationDate: new Date('February 16, 1954'), synopsis: "The story is about a young English boy, Denis, who, while in France falls under the influence of a vampiric being, from the folklore of Auvergne and the misfortune that befalls him.", tagId: null, coverArt: "../images/feasting_dead.jpg", createdAt: new Date(), updatedAt: new Date()},
      {author: 'William Hope Hodgson', title: 'The Ghost Pirates', publisher: 'Stanley Paul', publicationDate: new Date('June 6, 1909'), synopsis: "In it, Hodgson never describes in any remarkable details the ghosts – if this is indeed what they are, since their true nature is left ambiguous – he merely reports on their gradual commandeering of the ship.", tagId: null, coverArt: "../images/ghost_pirates.jpg", createdAt: new Date(), updatedAt: new Date()},
      {author: 'Kim Wilkins', title: 'Giants of the Frost', publisher: 'Voyager', publicationDate: new Date('April 28, 2004'), synopsis: "It follows the story of Victoria Scott who after accepting a job on an isolated island is visited by a hag in her nightmares and a sense of familiarity in the haunted forest. In the world of Asgard, Vidar has exiled himself in order to await the reincarnation of the woman he loved", tagId: null, coverArt: "../images/giants-of-the-frost.png", createdAt: new Date(), updatedAt: new Date()},
      {author: 'José Guadalupe Posada', title: 'A Good and Happy Child', publisher: 'Crown Publishing Group', publicationDate: new Date('May 22, 2007'), synopsis: "Thirty-year-old George Davies can’t bring himself to hold his newborn son. After months of accepting his lame excuses and strange behavior, his wife, Maggie, has had enough. She demands that he see a therapist, and George, desperate to save his unraveling marriage and redeem himself as a father and husband, reluctantly agrees. This brings him into the office of Dr. H. Surman in Manhattan. In this office, George is tasked with keeping notebooks, which he uses to talk about supernatural incidents that happened when he was 11-years-old in Preston, Virginia.", tagId: null, coverArt: "../images/a-good-and-happy-child.jpg", createdAt: new Date(), updatedAt: new Date()},
      {author: 'Tananarive Due', title: 'The Good House', publisher: 'Washington Square', publicationDate: new Date('November 23, 2003'), synopsis: "The home that belonged to Angela Toussaint's late grandmother is so beloved that townspeople in Sacajawea, Washington, call it the Good House. But that all changes one summer when an unexpected tragedy takes place behind its closed doors...and the Toussaint's family history -- and future -- is dramatically transformed. Angela has not returned to the Good House since her son, Corey, died there two years ago. But now, Angela is finally ready to return to her hometown and go beyond the grave to unearth the truth about Corey's death.", tagId: null, coverArt: "../images/the-good-house.jpg", createdAt: new Date(), updatedAt: new Date()},
      {author: 'Maurice Renard', title: "Les Mains d' Orlac", publisher: "L'Intransigeant", publicationDate: new Date('July 12, 1920'), synopsis: "In the novel, the pianist Stephen Orlac suffers a railway accident that gives him serious head injuries and deprives him of his hands. The famous and controversial transplant doctor Cerral gives him new hands, transplanted from a freshly guillotined assassin. Afterward, Orlac begins to wonder if he has become a Mr. Hyde who has inherited the criminal proclivities of his donor via his hands.", tagId: null, coverArt: "../images/les-mains-d-orlac.jpg", createdAt: new Date(), updatedAt: new Date()},
      {author: 'R. L. Stine', title: 'Fear Street the New Girl', publisher: 'Simon Pulse', publicationDate: new Date('August 17, 1989'), synopsis: "Cory, a high school student, falls in love with Anna, a new girl at his school. As he tried to learn more about her, he begins to doubt her existence: most of his friends have never seen her on campus, and she's not listed in the school's files. When he calls her family's home someone on the other end insists that Anna is dead.", tagId: null, coverArt: "../images/fear-street.jpg", createdAt: new Date(), updatedAt: new Date()},
      {author: 'Stephen King', title: 'Cujo', publisher: 'Viking Press', publicationDate: new Date('September 8, 1981'), synopsis: "The story takes place in the setting for many King stories: the fictional town of Castle Rock, Maine. Revolving around two local families, the narrative is interspersed with vignettes from the seemingly mundane lives of various other residents. There are no chapter headings, but breaks between passages indicate when the narration switches to a different perspective.", tagId: null, coverArt: "../images/cujo.jpg", createdAt: new Date(), updatedAt: new Date()},      {author: 'Stephen King', title: 'The Dead Zone', publisher: 'Viking Press', publicationDate: new Date('August 30, 1979'), synopsis: "The story follows Johnny Smith, who awakens from a coma of nearly five years and now experiences clairvoyant and precognitive visions triggered by touch. These visions have limitations and when information is beyond his perception, Johnny refers to that information as being trapped in the part of his brain that is permanently damaged, the dead zone. The novel also follows Smith's search for a serial killer in Castle Rock, and the life of Greg Stillson, a rising politician, both of whom are evils Johnny must eventually face.", tagId: null, coverArt: "../images/dead-zone.jpg", createdAt: new Date(), updatedAt: new Date()},
      {author: 'Stephen King', title: 'Firestarter', publisher: 'Viking Press', publicationDate: new Date('September 29, 1980'), synopsis: "Andy and Charlene Charlie McGee are a father/daughter pair on the run from a government agency known as The Shop. During his college years, Andy had participated in a Shop experiment dealing with Lot 6, a drug with hallucinogenic effects similar to LSD. The drug gave his future wife, Victoria Tomlinson, minor telekinetic abilities and him a telepathic form of mind control he refers to as the push. They both also developed telepathic abilities. Andy's and Vicky's powers were physiologically limited; in his case, overuse of the push gives him crippling migraine headaches and minute brain hemorrhages, but their daughter Charlie developed frightening pyrokinetic ability.", tagId: null, coverArt: "../images/firestarter.jpg", createdAt: new Date(), updatedAt: new Date()},
      {author: 'Stephen King', title: 'Pet Cemetary', publisher: 'Doubleday', publicationDate: new Date('November 14, 1983'), synopsis: "Louis Creed, a doctor from Chicago, is appointed director of the University of Maine's campus health service. He moves to a large house near the small town of Ludlow with his wife Rachel, their two young children, Ellie and Gage, and Ellie's cat, Church. From the moment they arrive, the family runs into trouble: Ellie hurts her knee, and Gage is stung by a bee. Their new neighbor, an elderly man named Jud Crandall, comes to help. He warns Louis and Rachel about the highway that runs past their house, which is frequented by speeding trucks.", tagId: null, coverArt: "../images/pet-cemetary.jpg", createdAt: new Date(), updatedAt: new Date()},
      {author: 'H.P. Lovecraft', title: 'The Call of Cthulu', publisher: 'Weird Tales', publicationDate: new Date('February 1, 1928'), synopsis: "The first seed of the story's first chapter The Horror in Clay came from one of Lovecraft's own dreams he had in 1919,[3] which he described briefly in two different letters sent to his friend Rheinhart Kleiner on May 21 and December 14, 1920. In the dream, Lovecraft is visiting an antiquity museum in Providence, attempting to convince the aged curator there to buy an odd bas-relief Lovecraft himself had sculpted, who initially scoffs at him for trying to sell something recently made to a museum of antique objects", tagId: null, coverArt: "../images/call-of-cthulu.jpg", createdAt: new Date(), updatedAt: new Date()},
      {author: 'H.P. Lovecraft', title: 'At the Mountains of Madness', publisher: 'Astounding Stories', publicationDate: new Date('February 1, 1936'), synopsis: "The story is recalled in a first-person perspective by the geologist William Dyer, a professor at Arkham's Miskatonic University, in the hope to prevent an important and much publicized scientific expedition to Antarctica. Throughout the course of his explanation, Dyer relates how he led a group of scholars from Miskatonic University on a previous expedition to Antarctica, during which they discovered ancient ruins and a dangerous secret, beyond a range of mountains higher than the Himalayas.", tagId: null, coverArt: "../images/at-the-mountains-of-madness.jpg", createdAt: new Date(), updatedAt: new Date()},
      {author: 'H.P. Lovecraft', title: 'The Shadow Out of Time', publisher: 'Astounding Stories', publicationDate: new Date('June 1, 1936'), synopsis: "The Shadow Out of Time indirectly tells of the Great Race of Yith, an extraterrestrial species with the ability to travel through space and time. The Yithians accomplish this by switching bodies with hosts from the intended spatial or temporal destination. The story implies that the effect, when seen from the outside, is similar to spiritual possession. The Yithians' original purpose was to study the history of various times and places, and they have amassed a library city that is filled with the past and future history of multiple races, including humans. Ultimately the Yithians use their ability to escape the destruction of their planet in another galaxy by switching bodies with a race of cone-shaped plant beings who lived 250 million years ago on Earth.", tagId: null, coverArt: "../images/shadow-out-of-time.jpg", createdAt: new Date(), updatedAt: new Date()},
      {author: 'Patricia McKissack', title: 'Ol Clip Clop', publisher: 'Holiday House', publicationDate: new Date('April 10, 2013'), synopsis: "a 2013 book by Patricia McKissack about John Leep, a stingy landlord, who cheats a tenant but then gets his come-uppance.", tagId: null, coverArt: "../images/ol-clip-clop.jpg", createdAt: new Date(), updatedAt: new Date()},
      {author: 'Clive Barker', title: 'The Scarlet Gospels', publisher: 'St Martins Press', publicationDate: new Date('May 19, 2015'), synopsis: "The world's last remaining magicians gather to resurrect Ragowski, a recently deceased member of their order who was killed by the Hell Priest. Ragowski informs them that the Priest is determined to obtain every source of magic known to man, and that their only hope of avoiding his fate is to give the Priest the location of all of their grimoires and talismans. The Hell Priest arrives, having been alerted by the spell that caused Ragowski's resurrection, and proceeds to degrade and massacre all of the magicians save for one, Felixson, whom he enslaves to use as a human servant.", tagId: null, coverArt: "../images/scarlet-gospels.jpg", createdAt: new Date(), updatedAt: new Date()},
      {author: 'Robert Swindells', title: 'Room 13', publisher: 'Doubleday', publicationDate: new Date('December 19, 1989'), synopsis: "Fliss Morgan has a nightmare on the night before her school trip, to Whitby. Every night Ellie-May Sunderland is drawn to the landing outside the mysterious Room 13, which does not seem to exist during the day. Fliss and her friends attempt to unravel the mystery of the room, and determine the identity of its sinister inhabitant.", tagId: null, coverArt: "../images/room-13.jpg", createdAt: new Date(), updatedAt: new Date()},
      {author: 'Garth Nix', title: 'The Ragwitch', publisher: 'Tor Books', publicationDate: new Date('October 5, 1990'), synopsis: "Julia and her brother, Paul, are spending a day by the beach when they discover a midden heap. They climb to the top, where Julia discovers a rag doll in a ball of feathers hidden in a nest. It turns out to be a powerful and evil witch, and it possesses Julia and spirits her away through a pyramid of fire. Paul manages to follow them and he finds himself in a strange country desperately unprepared for the return of the Ragwitch.", tagId: null, coverArt: "../images/ragwitch.jpg", createdAt: new Date(), updatedAt: new Date()},
      {author: 'Gaston Leroux', title: "Le Fantome de l'Opera", publisher: 'Pierre Laie', publicationDate: new Date('September 23, 1909'), synopsis: "In Paris in the 1880s, the Palais Garnier Opera House is believed to be haunted by an entity known as the Phantom of the Opera, or simply the Opera Ghost. A stagehand named Joseph Buquet is found hanged and the noose around his neck goes missing.", tagId: null, coverArt: "../images/phantom-of-the-opera.jpg", createdAt: new Date(), updatedAt: new Date()},
      {author: 'Guillermo del Toro', title: 'The Night Eternal', publisher: 'William Morrow and Company', publicationDate: new Date('October 25, 2011'), synopsis: "Two years have passed since the vampires, led by the Master, used atomic weapons to create a nuclear winter, which blocked the sun and allowed the vampires to move freely, except for a few hours a day. The vampires restructured society as a police state. The strongest and the most influential humans were exterminated and those who were spared were made slaves. The weak were forced into camps to harvest their blood.", tagId: null, coverArt: "../images/night-eternal.jpg", createdAt: new Date(), updatedAt: new Date()}
    ], {});
  },

  down: (queryInterface, Sequelize) => {
  return queryInterface.bulkDelete('Books', null, {});
  }
};
